//
//  BuildConfig.swift
//  WebRTCTestBed
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  This file is generated by scripts/generate-build-config.sh
//  Values are injected at build time from environment variables.
//

import Foundation

/// Build-time configuration values injected from CI/build environment.
/// These serve as defaults and can be overridden by user settings.
enum BuildConfig {
    /// SDK License Key - injected from R5PRO_LICENSE environment variable
    static let license: String = "XXXX-XXXX-XXXX-XXXX"
    
    /// License Manager - injected from R5PRO_LICENSE_MANAGER environment variable
    static let licenseManager: String = "license.XXXX.net"
}
