name: TestBed
options:
  bundleIdPrefix: com.red5

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: 114.0.0
  Red5WebRTCKit:
    path: /Users/mustafaboleken/Documents/GitHub/red5pro-ios-sdk/Red5WebRTCKit

targets:
  TestBed:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
    info:
      path: Resources/Info.plist
    settings:
      base:
        PRODUCT_NAME: TestBed
    dependencies:
      - package: WebRTC
      - package: Red5WebRTCKit

  TestBedTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES      # ← auto-generate
    dependencies:
      - target: TestBed
      - package: Red5WebRTCKit
      - package: WebRTC

 TestBedUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES      # ← auto-generate
    dependencies:
      - target: TestBed   # UI tests run your app target

schemes:
  TestBed:
    build:
      targets:
        TestBed: all
        TestBedTests: test
        TestBedUITests: test
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: TestBedTests
        - name: TestBedUITests
