#!/bin/bash

#===============================================================================
# Build Configuration Generator
#
# Generates BuildConfig.swift with values from environment variables.
# This script should be run before building the Xcode project.
#
# Environment Variables:
#   - R5PRO_LICENSE: SDK license key (optional, defaults to empty)
#   - R5PRO_LICENSE_MANAGER: License manager URL (optional, defaults to empty)
#
# Usage:
#   ./scripts/generate-build-config.sh
#
# Or with environment variables:
#   R5PRO_LICENSE="XXX-XXX" R5PRO_LICENSE_MANAGER="https://..." ./scripts/generate-build-config.sh
#===============================================================================

set -euo pipefail

# Configuration
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${PROJECT_DIR}/WebRTCTestBed/BuildConfig.swift"

# Get values from environment (default to empty string)
LICENSE="${R5PRO_LICENSE:-}"
LICENSE_MANAGER="${R5PRO_LICENSE_MANAGER:-}"

if [[ -f "${OUTPUT_FILE}" ]]; then
    rm -f "${OUTPUT_FILE}"
fi

# Generate the Swift file
cat > "${OUTPUT_FILE}" << EOF
//
//  BuildConfig.swift
//  WebRTCTestBed
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  This file is generated by scripts/generate-build-config.sh
//  Values are injected at build time from environment variables.
//

import Foundation

/// Build-time configuration values injected from CI/build environment.
/// These serve as defaults and can be overridden by user settings.
enum BuildConfig {
    /// SDK License Key - injected from R5PRO_LICENSE environment variable
    static let license: String = "${LICENSE}"
    
    /// Stream Manager Endpoint - injected from R5PRO_ENDPOINT environment variable
    static let licenseManager: String = "${LICENSE_MANAGER}"
}
EOF

echo "[INFO] Generated BuildConfig.swift"
if [[ -n "${LICENSE}" ]]; then
    echo "[INFO]   - License: [REDACTED - ${#LICENSE} chars]"
else
    echo "[INFO]   - License: (not set)"
fi
if [[ -n "${LICENSE_MANAGER}" ]]; then
    echo "[INFO]   - License Manager: ${LICENSE_MANAGER}"
else
    echo "[INFO]   - License Manager: (not set)"
fi
